### ISSUE TITLE
Calling depends_on :java is deprecated

### ISSUE THREAD

**Issue by davismmarques** [MartinDelille/homebrew-tap#1]
Brew emits the following warning when installing from your tap:

> Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
> Please report this issue to the martindelille/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
>   /usr/local/Homebrew/Library/Taps/martindelille/homebrew-tap/openapi-generator@4.2.2.rb:15

As noted above, the suggested fix is to replace :java with openjdk or similar.

**Comment by MartinDelille** [comment]
Ok thank you for the feedback! I remove the formula containing the warning because I don't use this version of `openapi-generator` anymore: 57c7d21
